---
title: "Ecohydrologische studie SBZ-deelzone Kesterbeekvallei (Hallerbos)"
author:
  - name:
      given: "Stijn"
      family: "Bruneel"
    email: "stijn.bruneel@inbo.be"
    orcid: "0000-0002-8226-8080"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
    corresponding: true
  - name:
      given: "Charlotte"
      family: "Van Driessche"
    email: "charlotte.vandriessche@inbo.be"
    orcid: "0000-0003-1606-8758"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
reviewer:
  - name:
      given: "Lore"
      family: "Vandamme"
    email: "lore.vandamme@inbo.be"
    orcid: "0009-0000-0500-9547"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
lang: nl
style: INBO
client:
  - VLM
floatbarrier: subsubsection
lof: TRUE
lot: TRUE
keywords: "kesterbeek; vis; hydromorfologie; oevers; edna; elektrisch vissen"
community: "inbo"
publication_type: report
funder: Instituut voor Natuur- en Bosonderzoek (INBO)
rightsholder: Instituut voor Natuur- en Bosonderzoek (INBO)
bibliography: references.bib
link-citations: TRUE
site: bookdown::bookdown_site
output:
  INBOmd::gitbook: default
  INBOmd::pdf_report: default
  INBOmd::epub_book: default
  bookdown::word_document2: default
# Don't run the format below.
# Only required for RStudio to recognise the project as a bookdown project.
# Hence don't use 'Build all formats'.
  bookdown::dontrun: default
---

# Dankwoord {.unnumbered}

De tekst voor het optionele dankwoord.

# Voorwoord {.unnumbered}

De tekst voor het optionele voorwoord.

# Samenvatting {.unnumbered}

<!-- description: start -->

De tekst voor de verplichte samenvatting.
Hou het [Heerlijk Helder](https://overheid.vlaanderen.be/communicatie/heerlijk-helder).
<!-- description: end -->

# Aanbevelingen voor beheer en/of beleid {.unnumbered}

Verplicht wanneer relevant.

```{r setup, include = FALSE}
library(knitr)
opts_chunk$set(
  echo = FALSE,
  eval = TRUE,
  cache = FALSE,
  warning = FALSE,
  error = FALSE,
  message = FALSE
)
library(tidyverse)
library(INBOtheme)
if (interactive()) {
  theme_set(theme_inbo(base_size = 10))
} else {
  switch(
    opts_knit$get("rmarkdown.pandoc.to"),
    html = {
      opts_chunk$set(dev = "png", dpi = 72)
      theme_set(theme_inbo(base_size = 12))
    },
    latex = {
      opts_chunk$set(dev = "cairo_pdf", dpi = 300)
      theme_set(theme_inbo(base_size = 9))
      update_geom_defaults("point", list(size = 1.5))
    },
    epub3 = {
      opts_chunk$set(dev = "png", dpi = 300)
      theme_set(theme_inbo(base_size = 12))
    }
  )
}
```

```{r}
knitr::opts_chunk$set(fig.width=10, fig.height=10) 
```
